version: "3.1"

services:
  wordpress:
    build: .
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
    env_file:
      - dbconnection.env
    environment:
      DB_HOST: mysql

    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file:
      - dbconnection.env
    volumes:
      - ~/mysqldb:/var/lib/mysql
